-- Creation of an empty table
CREATE OR REPLACE TABLE "dim_country" (
	"country_dwid" TEXT NOT NULL, 
	"name" TEXT NOT NULL, 
	"display_name" TEXT NOT NULL, 
	"m49_code" TEXT NOT NULL, 
	"iso_alpha2_code" TEXT NOT NULL, 
	"iso_alpha3_code" TEXT NOT NULL, 
	"geo_region_name" TEXT NOT NULL, 
	"geo_sub_region_name" TEXT NOT NULL, 
	"geo_intermediate_region_name" TEXT NOT NULL, 
	"region_name" TEXT NOT NULL 
);

-- Inserting static data into the output table
INSERT OVERWRITE INTO "dim_country" (
	"country_dwid", 
	"name", 
	"display_name", 
	"m49_code", 
	"iso_alpha2_code", 
	"iso_alpha3_code", 
	"geo_region_name", 
	"geo_sub_region_name", 
	"geo_intermediate_region_name", 
	"region_name" 
) VALUES  
('-1','Unknown','Unknown','','','','Unknown','Unknown','Unknown','Unknown'),
('-2','Global','Global','','','','Global','Global','Global','Global'),
('1','Algeria','Algeria','12','DZ','DZA','Africa','Northern Africa','','Africa'),
('2','Egypt','Egypt','818','EG','EGY','Africa','Northern Africa','','Africa'),
('3','Libya','Libya','434','LY','LBY','Africa','Northern Africa','','Africa'),
('4','Morocco','Morocco','504','MA','MAR','Africa','Northern Africa','','Africa'),
('5','Sudan','Sudan','729','SD','SDN','Africa','Northern Africa','','Africa'),
('6','Tunisia','Tunisia','788','TN','TUN','Africa','Northern Africa','','Africa'),
('9','Burundi','Burundi','108','BI','BDI','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('10','Comoros','Comoros','174','KM','COM','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('11','Djibouti','Djibouti','262','DJ','DJI','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('12','Eritrea','Eritrea','232','ER','ERI','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('13','Ethiopia','Ethiopia','231','ET','ETH','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('15','Kenya','Kenya','404','KE','KEN','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('16','Madagascar','Madagascar','450','MG','MDG','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('17','Malawi','Malawi','454','MW','MWI','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('18','Mauritius','Mauritius','480','MU','MUS','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('20','Mozambique','Mozambique','508','MZ','MOZ','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('22','Rwanda','Rwanda','646','RW','RWA','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('23','Seychelles','Seychelles','690','SC','SYC','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('24','Somalia','Somalia','706','SO','SOM','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('25','South Sudan','South Sudan','728','SS','SSD','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('26','Uganda','Uganda','800','UG','UGA','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('27','United Republic of Tanzania','United Republic of Tanzania','834','TZ','TZA','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('28','Zambia','Zambia','894','ZM','ZMB','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('29','Zimbabwe','Zimbabwe','716','ZW','ZWE','Africa','Sub-Saharan Africa','Eastern Africa','Africa'),
('30','Angola','Angola','24','AO','AGO','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('31','Cameroon','Cameroon','120','CM','CMR','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('32','Central African Republic','Central African Republic','140','CF','CAF','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('33','Chad','Chad','148','TD','TCD','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('34','Congo','Congo','178','CG','COG','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('35','Democratic Republic of the Congo','Democratic Republic of the Congo','180','CD','COD','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('36','Equatorial Guinea','Equatorial Guinea','226','GQ','GNQ','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('37','Gabon','Gabon','266','GA','GAB','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('38','Sao Tome and Principe','Sao Tome and Principe','678','ST','STP','Africa','Sub-Saharan Africa','Middle Africa','Africa'),
('39','Botswana','Botswana','72','BW','BWA','Africa','Sub-Saharan Africa','Southern Africa','Africa'),
('40','Eswatini','Eswatini','748','SZ','SWZ','Africa','Sub-Saharan Africa','Southern Africa','Africa'),
('41','Lesotho','Lesotho','426','LS','LSO','Africa','Sub-Saharan Africa','Southern Africa','Africa'),
('42','Namibia','Namibia','516','NA','NAM','Africa','Sub-Saharan Africa','Southern Africa','Africa'),
('43','South Africa','South Africa','710','ZA','ZAF','Africa','Sub-Saharan Africa','Southern Africa','Africa'),
('44','Benin','Benin','204','BJ','BEN','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('45','Burkina Faso','Burkina Faso','854','BF','BFA','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('46','Cabo Verde','Cabo Verde','132','CV','CPV','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('47','Côte d’Ivoire','Côte d’Ivoire','384','CI','CIV','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('48','Gambia','Gambia','270','GM','GMB','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('49','Ghana','Ghana','288','GH','GHA','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('50','Guinea','Guinea','324','GN','GIN','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('51','Guinea-Bissau','Guinea-Bissau','624','GW','GNB','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('52','Liberia','Liberia','430','LR','LBR','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('53','Mali','Mali','466','ML','MLI','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('54','Mauritania','Mauritania','478','MR','MRT','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('55','Niger','Niger','562','NE','NER','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('56','Nigeria','Nigeria','566','NG','NGA','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('58','Senegal','Senegal','686','SN','SEN','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('59','Sierra Leone','Sierra Leone','694','SL','SLE','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('60','Togo','Togo','768','TG','TGO','Africa','Sub-Saharan Africa','Western Africa','Africa'),
('62','Antigua and Barbuda','Antigua and Barbuda','28','AG','ATG','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('64','Bahamas','Bahamas','44','BS','BHS','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('65','Barbados','Barbados','52','BB','BRB','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('69','Cuba','Cuba','192','CU','CUB','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('71','Dominica','Dominica','212','DM','DMA','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('72','Dominican Republic','Dominican Republic','214','DO','DOM','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('73','Grenada','Grenada','308','GD','GRD','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('75','Haiti','Haiti','332','HT','HTI','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('76','Jamaica','Jamaica','388','JM','JAM','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('81','Saint Kitts and Nevis','Saint Kitts and Nevis','659','KN','KNA','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('82','Saint Lucia','Saint Lucia','662','LC','LCA','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('84','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','670','VC','VCT','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('86','Trinidad and Tobago','Trinidad and Tobago','780','TT','TTO','Americas','Latin America and the Caribbean','Caribbean','LATAM'),
('89','Belize','Belize','84','BZ','BLZ','Americas','Latin America and the Caribbean','Central America','LATAM'),
('90','Costa Rica','Costa Rica','188','CR','CRI','Americas','Latin America and the Caribbean','Central America','LATAM'),
('91','El Salvador','El Salvador','222','SV','SLV','Americas','Latin America and the Caribbean','Central America','LATAM'),
('92','Guatemala','Guatemala','320','GT','GTM','Americas','Latin America and the Caribbean','Central America','LATAM'),
('93','Honduras','Honduras','340','HN','HND','Americas','Latin America and the Caribbean','Central America','LATAM'),
('94','Mexico','Mexico','484','MX','MEX','Americas','Latin America and the Caribbean','Central America','LATAM'),
('95','Nicaragua','Nicaragua','558','NI','NIC','Americas','Latin America and the Caribbean','Central America','LATAM'),
('96','Panama','Panama','591','PA','PAN','Americas','Latin America and the Caribbean','Central America','LATAM'),
('97','Argentina','Argentina','32','AR','ARG','Americas','Latin America and the Caribbean','South America','LATAM'),
('98','Bolivia (Plurinational State of)','Bolivia (Plurinational State of)','68','BO','BOL','Americas','Latin America and the Caribbean','South America','LATAM'),
('100','Brazil','Brazil','76','BR','BRA','Americas','Latin America and the Caribbean','South America','LATAM'),
('101','Chile','Chile','152','CL','CHL','Americas','Latin America and the Caribbean','South America','LATAM'),
('102','Colombia','Colombia','170','CO','COL','Americas','Latin America and the Caribbean','South America','LATAM'),
('103','Ecuador','Ecuador','218','EC','ECU','Americas','Latin America and the Caribbean','South America','LATAM'),
('106','Guyana','Guyana','328','GY','GUY','Americas','Latin America and the Caribbean','South America','LATAM'),
('107','Paraguay','Paraguay','600','PY','PRY','Americas','Latin America and the Caribbean','South America','LATAM'),
('108','Peru','Peru','604','PE','PER','Americas','Latin America and the Caribbean','South America','LATAM'),
('110','Suriname','Suriname','740','SR','SUR','Americas','Latin America and the Caribbean','South America','LATAM'),
('111','Uruguay','Uruguay','858','UY','URY','Americas','Latin America and the Caribbean','South America','LATAM'),
('112','Venezuela (Bolivarian Republic of)','Venezuela (Bolivarian Republic of)','862','VE','VEN','Americas','Latin America and the Caribbean','South America','LATAM'),
('114','Canada','Canada','124','CA','CAN','Americas','Northern America','','North America'),
('117','United States of America','United States','840','US','USA','Americas','Northern America','','North America'),
('119','Kazakhstan','Kazakhstan','398','KZ','KAZ','Asia','Central Asia','','APAC'),
('120','Kyrgyzstan','Kyrgyzstan','417','KG','KGZ','Asia','Central Asia','','APAC'),
('121','Tajikistan','Tajikistan','762','TJ','TJK','Asia','Central Asia','','APAC'),
('122','Turkmenistan','Turkmenistan','795','TM','TKM','Asia','Central Asia','','APAC'),
('123','Uzbekistan','Uzbekistan','860','UZ','UZB','Asia','Central Asia','','APAC'),
('124','China','China','156','CN','CHN','Asia','Eastern Asia','','APAC'),
('127',$$Democratic People's Republic of Korea$$,$$Democratic People's Republic of Korea$$,'408','KP','PRK','Asia','Eastern Asia','','APAC'),
('128','Japan','Japan','392','JP','JPN','Asia','Eastern Asia','','APAC'),
('129','Mongolia','Mongolia','496','MN','MNG','Asia','Eastern Asia','','APAC'),
('130','Republic of Korea','Republic of Korea','410','KR','KOR','Asia','Eastern Asia','','APAC'),
('131','Brunei Darussalam','Brunei Darussalam','96','BN','BRN','Asia','South-eastern Asia','','APAC'),
('132','Cambodia','Cambodia','116','KH','KHM','Asia','South-eastern Asia','','APAC'),
('133','Indonesia','Indonesia','360','ID','IDN','Asia','South-eastern Asia','','APAC'),
('134',$$Lao People's Democratic Republic$$,$$Lao People's Democratic Republic$$,'418','LA','LAO','Asia','South-eastern Asia','','APAC'),
('135','Malaysia','Malaysia','458','MY','MYS','Asia','South-eastern Asia','','APAC'),
('136','Myanmar','Myanmar','104','MM','MMR','Asia','South-eastern Asia','','APAC'),
('137','Philippines','Philippines','608','PH','PHL','Asia','South-eastern Asia','','APAC'),
('138','Singapore','Singapore','702','SG','SGP','Asia','South-eastern Asia','','APAC'),
('139','Thailand','Thailand','764','TH','THA','Asia','South-eastern Asia','','APAC'),
('140','Timor-Leste','Timor-Leste','626','TL','TLS','Asia','South-eastern Asia','','APAC'),
('141','Viet Nam','Viet Nam','704','VN','VNM','Asia','South-eastern Asia','','APAC'),
('142','Afghanistan','Afghanistan','4','AF','AFG','Asia','Southern Asia','','APAC'),
('143','Bangladesh','Bangladesh','50','BD','BGD','Asia','Southern Asia','','APAC'),
('144','Bhutan','Bhutan','64','BT','BTN','Asia','Southern Asia','','APAC'),
('145','India','India','356','IN','IND','Asia','Southern Asia','','APAC'),
('146','Iran (Islamic Republic of)','Iran (Islamic Republic of)','364','IR','IRN','Asia','Southern Asia','','APAC'),
('147','Maldives','Maldives','462','MV','MDV','Asia','Southern Asia','','APAC'),
('148','Nepal','Nepal','524','NP','NPL','Asia','Southern Asia','','APAC'),
('149','Pakistan','Pakistan','586','PK','PAK','Asia','Southern Asia','','APAC'),
('150','Sri Lanka','Sri Lanka','144','LK','LKA','Asia','Southern Asia','','APAC'),
('151','Armenia','Armenia','51','AM','ARM','Asia','Western Asia','','EMEA'),
('152','Azerbaijan','Azerbaijan','31','AZ','AZE','Asia','Western Asia','','EMEA'),
('153','Bahrain','Bahrain','48','BH','BHR','Asia','Western Asia','','EMEA'),
('154','Cyprus','Cyprus','196','CY','CYP','Asia','Western Asia','','EMEA'),
('155','Georgia','Georgia','268','GE','GEO','Asia','Western Asia','','EMEA'),
('156','Iraq','Iraq','368','IQ','IRQ','Asia','Western Asia','','EMEA'),
('157','Israel','Israel','376','IL','ISR','Asia','Western Asia','','EMEA'),
('158','Jordan','Jordan','400','JO','JOR','Asia','Western Asia','','EMEA'),
('159','Kuwait','Kuwait','414','KW','KWT','Asia','Western Asia','','EMEA'),
('160','Lebanon','Lebanon','422','LB','LBN','Asia','Western Asia','','EMEA'),
('161','Oman','Oman','512','OM','OMN','Asia','Western Asia','','EMEA'),
('162','Qatar','Qatar','634','QA','QAT','Asia','Western Asia','','EMEA'),
('163','Saudi Arabia','Saudi Arabia','682','SA','SAU','Asia','Western Asia','','EMEA'),
('165','Syrian Arab Republic','Syrian Arab Republic','760','SY','SYR','Asia','Western Asia','','EMEA'),
('166','Turkey','Turkey','792','TR','TUR','Asia','Western Asia','','EMEA'),
('167','United Arab Emirates','United Arab Emirates','784','AE','ARE','Asia','Western Asia','','EMEA'),
('168','Yemen','Yemen','887','YE','YEM','Asia','Western Asia','','EMEA'),
('169','Belarus','Belarus','112','BY','BLR','Europe','Eastern Europe','','EMEA'),
('170','Bulgaria','Bulgaria','100','BG','BGR','Europe','Eastern Europe','','EMEA'),
('171','Czechia','Czech Republic','203','CZ','CZE','Europe','Eastern Europe','','EMEA'),
('172','Hungary','Hungary','348','HU','HUN','Europe','Eastern Europe','','EMEA'),
('173','Poland','Poland','616','PL','POL','Europe','Eastern Europe','','EMEA'),
('174','Republic of Moldova','Republic of Moldova','498','MD','MDA','Europe','Eastern Europe','','EMEA'),
('175','Romania','Romania','642','RO','ROU','Europe','Eastern Europe','','EMEA'),
('176','Russian Federation','Russian Federation','643','RU','RUS','Europe','Eastern Europe','','EMEA'),
('177','Slovakia','Slovakia','703','SK','SVK','Europe','Eastern Europe','','EMEA'),
('178','Ukraine','Ukraine','804','UA','UKR','Europe','Eastern Europe','','EMEA'),
('183','Denmark','Denmark','208','DK','DNK','Europe','Northern Europe','','EMEA'),
('184','Estonia','Estonia','233','EE','EST','Europe','Northern Europe','','EMEA'),
('186','Finland','Finland','246','FI','FIN','Europe','Northern Europe','','EMEA'),
('187','Iceland','Iceland','352','IS','ISL','Europe','Northern Europe','','EMEA'),
('188','Ireland','Ireland','372','IE','IRL','Europe','Northern Europe','','EMEA'),
('190','Latvia','Latvia','428','LV','LVA','Europe','Northern Europe','','EMEA'),
('191','Lithuania','Lithuania','440','LT','LTU','Europe','Northern Europe','','EMEA'),
('192','Norway','Norway','578','NO','NOR','Europe','Northern Europe','','EMEA'),
('194','Sweden','Sweden','752','SE','SWE','Europe','Northern Europe','','EMEA'),
('195','United Kingdom of Great Britain and Northern Ireland','United Kingdom','826','GB','GBR','Europe','Northern Europe','','EMEA'),
('196','Albania','Albania','8','AL','ALB','Europe','Southern Europe','','EMEA'),
('197','Andorra','Andorra','20','AD','AND','Europe','Southern Europe','','EMEA'),
('198','Bosnia and Herzegovina','Bosnia and Herzegovina','70','BA','BIH','Europe','Southern Europe','','EMEA'),
('199','Croatia','Croatia','191','HR','HRV','Europe','Southern Europe','','EMEA'),
('201','Greece','Greece','300','GR','GRC','Europe','Southern Europe','','EMEA'),
('203','Italy','Italy','380','IT','ITA','Europe','Southern Europe','','EMEA'),
('204','Malta','Malta','470','MT','MLT','Europe','Southern Europe','','EMEA'),
('205','Montenegro','Montenegro','499','ME','MNE','Europe','Southern Europe','','EMEA'),
('206','North Macedonia','North Macedonia','807','MK','MKD','Europe','Southern Europe','','EMEA'),
('207','Portugal','Portugal','620','PT','PRT','Europe','Southern Europe','','EMEA'),
('208','San Marino','San Marino','674','SM','SMR','Europe','Southern Europe','','EMEA'),
('209','Serbia','Serbia','688','RS','SRB','Europe','Southern Europe','','EMEA'),
('210','Slovenia','Slovenia','705','SI','SVN','Europe','Southern Europe','','EMEA'),
('211','Spain','Spain','724','ES','ESP','Europe','Southern Europe','','EMEA'),
('212','Austria','Austria','40','AT','AUT','Europe','Western Europe','','EMEA'),
('213','Belgium','Belgium','56','BE','BEL','Europe','Western Europe','','EMEA'),
('214','France','France','250','FR','FRA','Europe','Western Europe','','EMEA'),
('215','Germany','Germany','276','DE','DEU','Europe','Western Europe','','EMEA'),
('216','Liechtenstein','Liechtenstein','438','LI','LIE','Europe','Western Europe','','EMEA'),
('217','Luxembourg','Luxembourg','442','LU','LUX','Europe','Western Europe','','EMEA'),
('218','Monaco','Monaco','492','MC','MCO','Europe','Western Europe','','EMEA'),
('219','Netherlands','Netherlands','528','NL','NLD','Europe','Western Europe','','EMEA'),
('220','Switzerland','Switzerland','756','CH','CHE','Europe','Western Europe','','EMEA'),
('221','Australia','Australia','36','AU','AUS','Oceania','Australia and New Zealand','','APAC'),
('225','New Zealand','New Zealand','554','NZ','NZL','Oceania','Australia and New Zealand','','APAC'),
('227','Fiji','Fiji','242','FJ','FJI','Oceania','Melanesia','','APAC'),
('229','Papua New Guinea','Papua New Guinea','598','PG','PNG','Oceania','Melanesia','','APAC'),
('230','Solomon Islands','Solomon Islands','90','SB','SLB','Oceania','Melanesia','','APAC'),
('231','Vanuatu','Vanuatu','548','VU','VUT','Oceania','Melanesia','','APAC'),
('233','Kiribati','Kiribati','296','KI','KIR','Oceania','Micronesia','','APAC'),
('234','Marshall Islands','Marshall Islands','584','MH','MHL','Oceania','Micronesia','','APAC'),
('235','Micronesia (Federated States of)','Micronesia (Federated States of)','583','FM','FSM','Oceania','Micronesia','','APAC'),
('236','Nauru','Nauru','520','NR','NRU','Oceania','Micronesia','','APAC'),
('238','Palau','Palau','585','PW','PLW','Oceania','Micronesia','','APAC'),
('245','Samoa','Samoa','882','WS','WSM','Oceania','Polynesia','','APAC'),
('247','Tonga','Tonga','776','TO','TON','Oceania','Polynesia','','APAC'),
('248','Tuvalu','Tuvalu','798','TV','TUV','Oceania','Polynesia','','APAC')
;